### ISSUE TITLE
Create 3 more pages (by copying the existing page (Home) three times) and rename the .html files accordingly.

### ISSUE THREAD

**Issue by Bruce773** [Bruce773/pcaps#2]
Then, update all of the links in all of the nav bars.

**Comment by Bruce773** [comment]
If you have any questions, you can just comment here.
Good luck, Vince!!

**Comment by VinceMead** [comment]
What do you mean by "update all of the links in all of the nav bars"

**Comment by Bruce773** [comment]
Once you create three more pages, you'll need to update the links in the nav bars on all three pages to link to the appropriate pages. I'd recommend copying the template.html page three times...

**Comment by VinceMead** [comment]
I'm still confused. :(

**Comment by Bruce773** [comment]
Currently, all of the links in the nav bar (in both the template and the home page) link to non-existent places... We need them to link to the new pages you'll create by copying the template three times.
Name each of the three new pages one of these names:
About
Projects
Contact

**Comment by VinceMead** [comment]
I think I figured it out

**Comment by VinceMead** [comment]
i also think im done

**Comment by Bruce773** [comment]
I can't see anything...
I don't think you made a commit after you changed stuff.
Make sure that you commit your changes, and then create a pull request.
If you're not sure how to do that there're TONS of YouTube videos on that.

**Comment by VinceMead** [comment]
Ok I committed the changes. Do you want me to attend the beginners class?

**Comment by Bruce773** [comment]
That looks FANTASTIC!!!
Awesome job, Vince!!
If you'd like to, it'd be great to have you there for the beginners class!!

**Comment by VinceMead** [comment]
I can't be there for the beginners class.

**Comment by Bruce773** [comment]
Okay
