### ISSUE TITLE
Change the copyright to say Pi Crafters

### ISSUE THREAD

**Issue by Bruce773** [Bruce773/pcaps#9]
The copyright header is at the bottom of every page on the site and currently says Bruce Johnson. It needs to be changed to say Pi Crafters. This must be changed on EVERY page.

**Comment by Comradefluffy** [comment]
done

**Comment by Bruce773** [comment]
Looks pretty good but can you change it from PI Crafters to Pi Crafters (make the i lowercase rather than uppercase)?
Thanks!! 👍
@Comradefluffy

**Comment by Comradefluffy** [comment]
done
